### ISSUE TITLE
.bun_repl_history does not exist on first run

### ISSUE THREAD

**Issue by bwasti** [jhmaster2000/bun-repl#1]
Error on first run:

```
(env) bwasti@bwasti-mbp shumai % bun-repl
 7 |     constructor(prompt: string = '> ', historyPath?: string) {
 8 |         super();
 9 |         this.prompt = process.env.BUN_REPL_PROMPT ?? prompt;
10 |         historyPath ||= `${process.env.BUN_INSTALL ?? os.homedir()}/.bun_repl_history`;
11 |
12 |         const historyLines = fs.readFileSync(historyPath, 'utf8').split('\n');
                                 ^
ENOENT: No such file or directory
   path: "/Users/bwasti/.bun/.bun_repl_history"
syscall: "open"
  errno: -2

      at new REPLManager (/Users/bwasti/.bun/install/global/node_modules/bun-repl/src/replmanager.ts:12:29)
      at /Users/bwasti/.bun/install/global/node_modules/bun-repl/src/repl.ts:70:13
```

Workaround is to add that file: `touch $HOME/.bun/.bun_repl_history`, but I think the repl should do that for us :)

**Comment by jhmaster2000** [comment]
Fix is live on [v1.2.1](https://github.com/jhmaster2000/bun-repl/releases/tag/1.2.1) (also on npm)
